#ifndef _ET_FLASH_OFFSET_H_
#define _ET_FLASH_OFFSET_H_
#include"ET1502B.h"

#ifdef ENABLE_GT24L16M1Y_UT
#define KEYID_START_ADDR 0x00000000
#else
#define KEYID_START_ADDR 0x00100000
#endif

#define FLASH_GET_LENGTH 110

#define MAC_VALID_TAG1 0xaa
#define MAC_VALID_TAG2 0x55
#define MAC_ADDRESS_LENGTH 6

#define TAG1_ADDR_OFFSET 0
#define TAG2_ADDR_OFFSET 1
#define KEYID_LENGHT_ADDR_OFFSET 2 //KEI ID LENGTHS
#define MAC_ADDRESS_ADDR_OFFSET 3
#define KEYID_DATA_ADDR_OFFSET (9)




#define COS_VERSION_TAG1_ADDR_OFFSET 40
#define COS_VERSION_TAG2_ADDR_OFFSET 41
#define COS_VERSION_LENGHT_ADDR_OFFSET 42
#define COS_VERSION_DATA_ADDR_OFFSET 43

#define ALARM_FLAG_OFFSET 89
#define ALARM_LENGTH_OFFSET 90
#define ALARM_DATA_OFFSET 91

#endif
